-- ═══════════════════════════════════════════════════
--  Remitos (Delivery Notes) Schema
-- ═══════════════════════════════════════════════════

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'REMITOS')
BEGIN
  CREATE TABLE REMITOS (
    REMITO_ID           INT IDENTITY(1,1) PRIMARY KEY,
    TIPO                VARCHAR(10)       NOT NULL CHECK (TIPO IN ('ENTRADA', 'SALIDA')),
    FECHA               DATETIME          NOT NULL DEFAULT GETDATE(),
    PTO_VTA             NVARCHAR(5)       NOT NULL DEFAULT '0001',
    NRO_REMITO          NVARCHAR(10)      NOT NULL DEFAULT '00000001',

    -- Cliente o Proveedor (según tipo)
    CLIENTE_ID          INT               NULL,
    PROVEEDOR_ID        INT               NULL,

    -- Depósito de origen/destino
    DEPOSITO_ID         INT               NULL,

    OBSERVACIONES       NVARCHAR(500)     NULL,
    SUBTOTAL            DECIMAL(18,2)     NOT NULL DEFAULT 0,
    TOTAL               DECIMAL(18,2)     NOT NULL DEFAULT 0,
    ANULADO             BIT               NOT NULL DEFAULT 0,
    USUARIO_ID          INT               NULL,
    FECHA_CREACION      DATETIME          NOT NULL DEFAULT GETDATE()
  );

  CREATE INDEX IX_REMITOS_TIPO ON REMITOS (TIPO);
  CREATE INDEX IX_REMITOS_FECHA ON REMITOS (FECHA);
  CREATE INDEX IX_REMITOS_CLIENTE ON REMITOS (CLIENTE_ID);
  CREATE INDEX IX_REMITOS_PROVEEDOR ON REMITOS (PROVEEDOR_ID);
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'REMITOS_ITEMS')
BEGIN
  CREATE TABLE REMITOS_ITEMS (
    ITEM_ID             INT IDENTITY(1,1) PRIMARY KEY,
    REMITO_ID           INT               NOT NULL,
    PRODUCTO_ID         INT               NOT NULL,
    CANTIDAD            DECIMAL(18,4)     NOT NULL,
    PRECIO_UNITARIO     DECIMAL(18,4)     NOT NULL DEFAULT 0,
    TOTAL_PRODUCTO      DECIMAL(18,4)     NOT NULL DEFAULT 0,
    DEPOSITO_ID         INT               NULL,

    CONSTRAINT FK_REMITOS_ITEMS_REMITO FOREIGN KEY (REMITO_ID) REFERENCES REMITOS(REMITO_ID)
  );

  CREATE INDEX IX_REMITOS_ITEMS_REMITO ON REMITOS_ITEMS (REMITO_ID);
END
GO
