-- ═══════════════════════════════════════════════════
--  Stock History — Schema for tracking stock changes
--  Registers every stock movement: sales, purchases,
--  manual adjustments, remitos, etc.
-- ═══════════════════════════════════════════════════

-- Run this migration to create the STOCK_HISTORIAL table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'STOCK_HISTORIAL')
BEGIN
  CREATE TABLE STOCK_HISTORIAL (
    HISTORIAL_ID     INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCTO_ID      INT NOT NULL,
    DEPOSITO_ID      INT NOT NULL,
    CANTIDAD_ANTERIOR DECIMAL(18,4) NOT NULL DEFAULT 0,
    CANTIDAD_NUEVA    DECIMAL(18,4) NOT NULL DEFAULT 0,
    DIFERENCIA        DECIMAL(18,4) NOT NULL DEFAULT 0,
    TIPO_OPERACION    VARCHAR(30) NOT NULL,  -- VENTA, COMPRA, AJUSTE_MANUAL, REMITO, NC_COMPRA, TRANSFERENCIA
    REFERENCIA_ID     INT NULL,              -- VENTA_ID, COMPRA_ID, etc.
    REFERENCIA_DETALLE VARCHAR(200) NULL,    -- Description like "Venta #123", "Ajuste manual"
    USUARIO_ID        INT NULL,
    FECHA             DATETIME NOT NULL DEFAULT GETDATE(),
    OBSERVACIONES     VARCHAR(500) NULL
  );

  CREATE INDEX IX_STOCK_HISTORIAL_PRODUCTO ON STOCK_HISTORIAL (PRODUCTO_ID, FECHA DESC);
  CREATE INDEX IX_STOCK_HISTORIAL_DEPOSITO ON STOCK_HISTORIAL (DEPOSITO_ID, FECHA DESC);
  CREATE INDEX IX_STOCK_HISTORIAL_FECHA ON STOCK_HISTORIAL (FECHA DESC);
END
GO
