-- ════════════════════════════════════════════════════════════════════════
--  migrate-gastos-servicios.sql
--    Idempotent creation / extension of GASTOS_SERVICIOS schema.
--
--  Existing desktop schema (kept as-is, only extra columns added):
--    GASTO_ID     INT IDENTITY PK
--    ENTIDAD      NVARCHAR(100)   NOT NULL    -- "EDESUR", "Aysa", "Sueldos"...
--    DESCRIPCION  NVARCHAR(255)   NULL
--    MONTO        DECIMAL(18,2)   NOT NULL
--    FECHA        DATETIME        NOT NULL
--    COMPRA_ID    INT             NULL
--
--  Web extras:
--    USUARIO_ID, PUNTO_VENTA_ID, EFECTIVO, DIGITAL, CHEQUES, CTA_CTE,
--    CATEGORIA, MOVIMIENTO_CAJA_ID
--
--  Junction table:
--    GASTOS_SERVICIOS_METODOS_PAGO  (GASTO_ID, METODO_PAGO_ID, MONTO)
-- ════════════════════════════════════════════════════════════════════════

-- ── 1) Master table ────────────────────────────────────────────────────
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GASTOS_SERVICIOS')
BEGIN
  CREATE TABLE GASTOS_SERVICIOS (
    GASTO_ID    INT IDENTITY(1,1) PRIMARY KEY,
    ENTIDAD     NVARCHAR(100)   NOT NULL,
    DESCRIPCION NVARCHAR(255)   NULL,
    MONTO       DECIMAL(18,2)   NOT NULL,
    FECHA       DATETIME        NOT NULL,
    COMPRA_ID   INT             NULL
  );
  PRINT '  ✓ Table GASTOS_SERVICIOS created';
END
ELSE
  PRINT '  • Table GASTOS_SERVICIOS already exists';

-- ── 2) Extra columns (idempotent) ──────────────────────────────────────
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'CATEGORIA')
  ALTER TABLE GASTOS_SERVICIOS ADD CATEGORIA NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'USUARIO_ID')
  ALTER TABLE GASTOS_SERVICIOS ADD USUARIO_ID INT NULL;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'PUNTO_VENTA_ID')
  ALTER TABLE GASTOS_SERVICIOS ADD PUNTO_VENTA_ID INT NULL;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'EFECTIVO')
  ALTER TABLE GASTOS_SERVICIOS ADD EFECTIVO DECIMAL(18,2) NOT NULL CONSTRAINT DF_GASTOS_SERVICIOS_EFECTIVO DEFAULT 0;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'DIGITAL')
  ALTER TABLE GASTOS_SERVICIOS ADD DIGITAL DECIMAL(18,2) NOT NULL CONSTRAINT DF_GASTOS_SERVICIOS_DIGITAL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'CHEQUES')
  ALTER TABLE GASTOS_SERVICIOS ADD CHEQUES DECIMAL(18,2) NOT NULL CONSTRAINT DF_GASTOS_SERVICIOS_CHEQUES DEFAULT 0;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'CTA_CTE')
  ALTER TABLE GASTOS_SERVICIOS ADD CTA_CTE DECIMAL(18,2) NOT NULL CONSTRAINT DF_GASTOS_SERVICIOS_CTA_CTE DEFAULT 0;

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('GASTOS_SERVICIOS') AND name = 'MOVIMIENTO_CAJA_ID')
  ALTER TABLE GASTOS_SERVICIOS ADD MOVIMIENTO_CAJA_ID INT NULL;

PRINT '  ✓ GASTOS_SERVICIOS columns ensured';

-- ── 3) Junction table (payment method breakdown) ───────────────────────
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'GASTOS_SERVICIOS_METODOS_PAGO')
BEGIN
  CREATE TABLE GASTOS_SERVICIOS_METODOS_PAGO (
    ID             INT IDENTITY(1,1) PRIMARY KEY,
    GASTO_ID       INT NOT NULL,
    METODO_PAGO_ID INT NOT NULL,
    MONTO          DECIMAL(18,2) NOT NULL
  );
  CREATE INDEX IX_GASTOS_SERVICIOS_METODOS_PAGO_GASTO_ID
    ON GASTOS_SERVICIOS_METODOS_PAGO (GASTO_ID);
  PRINT '  ✓ Table GASTOS_SERVICIOS_METODOS_PAGO created';
END
ELSE
  PRINT '  • Table GASTOS_SERVICIOS_METODOS_PAGO already exists';

-- ── 4) Helper index on FECHA ───────────────────────────────────────────
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_GASTOS_SERVICIOS_FECHA' AND object_id = OBJECT_ID('GASTOS_SERVICIOS'))
  CREATE INDEX IX_GASTOS_SERVICIOS_FECHA ON GASTOS_SERVICIOS (FECHA DESC);

PRINT '✅ migrate-gastos-servicios.sql completed';
