import { Router } from 'express';
import authRoutes from './auth.routes.js';
import usuariosRoutes from './usuarios.routes.js';
import productRoutes from './product.routes.js';
import customerRoutes from './customer.routes.js';
import salesRoutes from './sales.routes.js';
import supplierRoutes from './supplier.routes.js';
import catalogRoutes from './catalog.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import cajaRoutes from './caja.routes.js';
import cajaCentralRoutes from './cajaCentral.routes.js';
import depositRoutes from './deposit.routes.js';
import puntoVentaRoutes from './puntoVenta.routes.js';
import categoryRoutes from './category.routes.js';
import brandRoutes from './brand.routes.js';
import ctaCorrienteRoutes from './ctaCorriente.routes.js';
import ctaCorrienteProvRoutes from './ctaCorrienteProv.routes.js';
import cobranzasRoutes from './cobranzas.routes.js';
import ordenesPagoRoutes from './ordenesPago.routes.js';
import purchasesRoutes from './purchases.routes.js';
import ncComprasRoutes from './ncCompras.routes.js';
import ncVentasRoutes from './ncVentas.routes.js';
import settingsRoutes from './settings.routes.js';
import mesasRoutes from './mesas.routes.js';
import paymentMethodRoutes from './paymentMethod.routes.js';
import remitosRoutes from './remitos.routes.js';
import stockRoutes from './stock.routes.js';
import libroIvaVentasRoutes from './libroIvaVentas.routes.js';
import libroIvaComprasRoutes from './libroIvaCompras.routes.js';
import mobileRoutes from './mobile.routes.js';
import afipRoutes from './afip.routes.js';
import expensesRoutes from './expenses.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/usuarios', usuariosRoutes);
router.use('/products', productRoutes);
router.use('/customers', customerRoutes);
router.use('/sales', salesRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/catalog', catalogRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/caja', cajaRoutes);
router.use('/caja-central', cajaCentralRoutes);
router.use('/deposits', depositRoutes);
router.use('/puntos-venta', puntoVentaRoutes);
router.use('/categories', categoryRoutes);
router.use('/brands', brandRoutes);
router.use('/cta-corriente', ctaCorrienteRoutes);
router.use('/cta-corriente-prov', ctaCorrienteProvRoutes);
router.use('/cobranzas', cobranzasRoutes);
router.use('/ordenes-pago', ordenesPagoRoutes);
router.use('/purchases', purchasesRoutes);
router.use('/nc-compras', ncComprasRoutes);
router.use('/nc-ventas', ncVentasRoutes);
router.use('/settings', settingsRoutes);
router.use('/mesas', mesasRoutes);
router.use('/payment-methods', paymentMethodRoutes);
router.use('/remitos', remitosRoutes);
router.use('/stock', stockRoutes);
router.use('/libro-iva-ventas', libroIvaVentasRoutes);
router.use('/libro-iva-compras', libroIvaComprasRoutes);
router.use('/mobile', mobileRoutes);
router.use('/afip', afipRoutes);
router.use('/expenses', expensesRoutes);

export default router;
