-- Top 50 productos más vendidos, ordenados por unidades.
-- SQL Server / SesamoDB

SELECT TOP 50
    p.PRODUCTO_ID,
    p.CODIGOPARTICULAR,
    p.NOMBRE,
    ISNULL(c.NOMBRE, 'Sin categoría')                    AS CATEGORIA,
    ISNULL(SUM(vi.CANTIDAD), 0)                          AS UNIDADES_VENDIDAS,
    ISNULL(SUM(vi.CANTIDAD * vi.PRECIO_UNITARIO), 0)     AS TOTAL_VENDIDO,
    COUNT(DISTINCT vi.VENTA_ID)                          AS VENTAS_DISTINTAS
FROM VENTAS_ITEMS vi
JOIN VENTAS v        ON vi.VENTA_ID   = v.VENTA_ID
JOIN PRODUCTOS p     ON vi.PRODUCTO_ID = p.PRODUCTO_ID
LEFT JOIN CATEGORIAS c ON p.CATEGORIA_ID = c.CATEGORIA_ID
GROUP BY p.PRODUCTO_ID, p.CODIGOPARTICULAR, p.NOMBRE, c.NOMBRE
ORDER BY UNIDADES_VENDIDAS DESC, TOTAL_VENDIDO DESC;